resources:
  - name: globaldot
    type: GitRepo
    configuration:
      gitProvider: github       
      path: DekelMalul/globaldots  
      sourceLocation: pythonlib
      
pipelines:
  - name: build python liabery
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: build
        type: Bash
        configuration:
          inputResources:
            - name: globaldot
        execution:
          onExecute:
            - pwd
            - ls -l
            - add_run_variables current_runid=$run_id
            - echo Previous run ID is $prev_runid
            - echo Current run ID is $current_runid
            - echo $res_myAppRepo_resourcePath
            - echo $res_myAppRepo_gitProvider_name
            - echo $res_myAppRepo_commitSha
 
      - name: push
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
 
 
