resources:
  - name: globaldot
    type: GitRepo
    configuration:
      gitProvider: github       
      path: DekelMalul/globaldots  
     
      
pipelines:
  - name: build_python_liabery
    steps:
      - name: build
        type: Bash
        configuration:
          inputResources:
            - name: globaldot
        execution:
          onExecute:
            - pwd
            - ls -l

      - name: push
        type: Bash
        configuration:
          inputSteps:
            - name:  build_python_liabery
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
 
 
