resources:
  - name: kayhut
    type: GitRepo
    configuration:
      gitProvider: github       
      path: DekelMalul/kayhut
      
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: pypi                       # <- Change to your integration name
      buildName: push
      buildNumber: 1  
      
pipelines:
  - name: build_python_liabery
    steps:
      - name: build
        type: Bash
        configuration:
          inputResources:
            - name: kayhut
        execution:
          onExecute:
            - git clone https://github.com/DekelMalul/kayhut.git
            - cd kayhut/pythonlib
            - pip install wheel setuptools 
            - python setup.py sdist bdist_wheel
            
     
      - name: push
        type: Bash
        configuration:
          inputSteps:
          - name: build
          integrations:
          - name: pypi
        execution:
          onExecute:
            - git clone https://github.com/DekelMalul/kayhut.git
            - cd kayhut/pythonlib
            - pip install twine
            - printenv int_pypi_url
           # - twine register -u dekelmalul@gmail.com -p AP5d2GKyYZ6DpaAyE9M3ZsLi3T6 --repository-url https://dekelartifactory.jfrog.io/artifactory/api/pypi/pypi strupper
            - twine upload  -u $int_pypi_user -p $int_pypi_apikey --repository-url $int_pypi_url dist/* 
