resources:
  - name: globaldot
    type: GitRepo
    configuration:
      gitProvider: github       
      path: DekelMalul/globaldots  
     
      
pipelines:
  - name: build_python_liabery
    steps:
      - name: build
        type: Bash
        configuration:
          inputResources:
            - name: globaldot
        execution:
          onExecute:
            - git clone https://github.com/DekelMalul/globaldots.git
            - cd pythonlib
            - python3 setup.py sdist bdist_wheel
            
     
      - name: push
        type: Bash
        configuration:
          inputSteps:
            - name: build
        execution:
          onExecute:
            - cd pythonlib
            - twine upload --config-file=.pypirc dist/*
 
 
